[build]
  publish = "."

[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Cache-Control = "public, max-age=300"

[[headers]]
  for = "/api/image/*"
  [headers.values]
    Cache-Control = "public, max-age=86400"
